export const sampledata = {
  title: "Childcare is broken: is the UK failing its future?(The Guardian)",
  url: "https://www.youtube.com/embed/qB8NBQokME0?si=GLNwcO-BxZ-VmdUn",
  subtitleList: [
    "do you think it's fixable or do we need to start again? ",
    " A nursery closes down forever So we're in a rainy Huyton, near Liverpool, where a nursery has shut its doors really suddenly. ",
    " 1:05 It was open on a Friday and then on the Saturday there was a sign on the gates saying that it closed for ever and 50 staff members found themselves out of a job. ",
    " 1:15 These children are broken hearted, they're confused. ",
    " 1:18 We have children sobbing here, holding on to each other. ",
    " 1:22 These children are suffering. ",
    " 1:24 Transition for children is very, very important and these children have had no transition. ",
    " 1:30 You took the decision at this nursery to unionise, why did you take that decision? ",
    " 1:35 Because we felt we had no other choice. ",
    " 1:38 We were being paid minimum wage, which is common throughout the sector. ",
    " 1:42 So many members of staff, including managers, have had second jobs. ",
    " 1:48 I've heard stories about people leaving leaving to go to Asda or Morrisons. ",
    " 1:52 Because they pay more money and we had to do something. ",
    " 1:55 After we took a day of strike action, the nursery owners basically closed the nursery down without any warning to parents, staff, children or anybody. ",
    ` 2:03 Every childcare worker, every care worker, needs to be standing up now and going: "I'm worth more than this." We need to stick together, if this can happen to us today, it can happen to you tomorrow. `,
    " 2:14 This isn't just a one-off. ",
    " What do you do when your childcare disappears? ",
    " 2:17 When The Orchard Day nursery locked its gates, around 200 children were suddenly left without childcare and parents had to scramble around for alternatives. ",
    " 2:35 Did you have any idea that this was going to happen? ",
    " 2:39 None, whatsoever. ",
    " 2:40 I actually couldn't believe that was allowed to happen. ",
    " 2:47 What's it been like for you? ",
    " 2:48 It's been a long two weeks, especially from a childcare perspective. ",
    " 2:54 Our parents work, so we don't have grandparents who can take Angus. ",
    " 2:58 I work with children of Angus's age. ",
    " 3:02 I spoke to my headteacher and he very, very kindly offered to let Angus attend the nursery setting. ",
    " 3:10 That must have been a relief. ",
    " 3:12 A huge relief. ",
    " 3:13 Other families do not have a support system around them and they've had to call in work and say we can't come to work today. ",
    " 3:21 They've lost money where they've paid upfront for the childcare and they've lost their pay. ",
    " 3:27 What's it been like putting your children into childcare and the kind of cost there's been around that? ",
    " 3:32 Our childcare has cost more than our rent each month. ",
    " 3:36 We paid around £12,000 last year. ",
    " 3:39 By the time the childcare had left my wages, I was actually working for maybe £300 per month. ",
    " 3:47 It's disheartening, isn't it? ",
    " 3:49 The thing is, Becci's situation is far from unique. ",
    " 3:52 Up and down the UK, parents are really struggling with childcare costs. ",
    " 3:57 Often, they look at the sums and they think it's not feasible, we can't do this Nursery fees and childcare reforms and so one of them, usually the mother, drops out of the workforce. ",
    " 4:05 But nurseries are really  struggling too and they say  they can't afford the increased cost of staffing, they can't afford the increased cost of energy and they are increasingly closing their doors. ",
    " 4:16 They say that the free hours that they provide at the moment aren't sufficiently funded by the government and haven't been for years. ",
    " 4:24 Now, the government has promised a revolution in childcare. ",
    " 4:28 It's promised over the next two years that parents will get more support with funding, more free hours, and nurseries will get paid more per hour for each child that goes there Pregnant Then Screwed and the March of the Mummies Groups like Pregnant Then Screwed have been campaigning for changes like these for years. ",
    " 4:48 Do you know how much it costs for a childcare place in the UK? ",
    " 4:52 It's about £14,000 a year. ",
    " 4:55 So what did that feel like, this moment here? ",
    " 4:58 I mean, just incredible. ",
    " 5:00 It's such a joyful expression of anger, which is what I think makes protests like these so important. ",
    " 5:09 Jeremy Hunt announced this huge new childcare package, what was your reaction? ",
    " 5:16 I was elated, I was really pleased. ",
    " 5:19 There are problems with it, of course, It's absolutely not without its flaws, however, the fact that it was the most significant part of the spring budget shows that childcare is being taken very seriously. ",
    " 5:32 How would you describe the current state of childcare in this country? ",
    " 5:37 I mean, it's a mess, it's just an absolute mess. ",
    " 5:42 It's unaffordable, it's inaccessible, it's entirely dysfunctional. ",
    " 5:47 There's nothing good about it and if we compare it to other countries, we are falling way way behind, embarrassingly so. ",
    " 5:55 Where does it better? ",
    " 5:57 Pretty much every country does it better than we do. ",
    " 6:01 No country though, I would say, has got it spot on. ",
    " 6:04 Countries tend to focus either on the quality of provision that they're providing and seeing it really as early years education or they see it as a way to get women back into the workforce. ",
    " 6:16 We are doing neither, we're failing at both. ",
    " 6:19 However, if they fail to deliver that first stage of this plan, it's political suicide. ",
    " 6:25 So yes, I am confident things will now get better. ",
    " 6:29 Can't really get any worse, can they? ",
    " 6:30 They can't get any worse, no, they really can't. ",
    " Childcare crisis in the UK So it's really difficult the spring budget. ",
    " 6:36 On the one hand, it will help many parents who are really struggling at the moment, but as someone who's covered this area a lot, I know that it's not as simple as that. ",
    ` 6:46 It's not as simple as: "Oh, this is going to fix everything," because what happens when you suddenly put loads more demand into this sector that is already teetering on the brink of collapse? `,
    " 6:58 So, we're going to go and speak to Neil Leitch, who is the CEO of the Early Years Alliance and see what he thinks about it. ",
    " 7:05 How would you describe the state of childcare in this country at the moment? ",
    " 7:10 Absolute crisis. ",
    " 7:11 This year we have seen record closures, nearly 5,500 providers have closed their doors. ",
    " 7:17 I've never witnessed the recruitment and retention crisis as grave as it is now. ",
    " 7:22 If this continues, you know, in commercial terms you would argue it would be a market collapse, but in real terms we prejudice the life chances of lots and lots of children. ",
    " 7:32 When you heard those announcements, what was your initial reaction? ",
    " 7:39 I probably couldn't explain on camera what my real reaction was, but definitely anger. ",
    " 7:45 None of this can be delivered. ",
    " 7:47 We have settings closing, we have settings reducing their hours, we have parents struggling to get access for their three- and four-year-olds. ",
    " 7:55 Why would you extend that even further, knowing that you can't cope with what you've got? ",
    " 8:00 All you've done is, dare I say, pile on more pressure. ",
    " 8:05 What do you think is going to happen in the next few years when this huge increase in demand is going to come into the sector? ",
    " 8:10 Well the logic says that there would be parents who will be turning up at settings, whether it be childminders, preschools or nurseries, expecting places for their children and they won't be there. ",
    " Madcaps nursery: we need ministers who care about early years education This is a sector that's in a lot of trouble. ",
    " 8:27 We know that nurseries are shutting their doors all the time, we know that other nurseries are really struggling to retain staff and they're just keeping their heads above water. ",
    " 8:39 We've come to Madcaps nursery in Lincolnshire, where the owner has had to take extreme measures just to keep the doors open. ",
    " 8:47 How long have you been open? ",
    " 8:48 We've been open about 12 years. ",
    " 8:50 We look at what's called the curiosity approach, so the children get their hands dirty, like they are over there and they really get to enjoy it. ",
    " 8:56 I can see, they're really getting into it here. ",
    " 8:59 She's busy planting things. ",
    " 9:01 What is it good early years education can bring to a child and to a family? ",
    " 9:06 Security, happiness, resilience. ",
    " 9:10 Children need to know how to deal with other people, how to deal with conflict, how to share. ",
    " 9:15 If you can give children that solid framework to start their lives, they've  got that for their life. ",
    " 9:23 How difficult has it been over the past couple of years as a provider? ",
    " 9:27 Awful. ",
    " 9:28 It's not an easy job, you've got a lot of skills, a lot of knowledge, a lot of experience and you're getting less money than somebody who works in our local supermarket, for example. ",
    " 9:36 It says what do you call a gorilla wearing headphones? ",
    " 9:40 A dancing gorilla. ",
    ` 9:42 It says "Anything you like, he can't hear you." Talk to us about how you've coped with the financial squeeze on the nursery. `,
    " 9:52 We've cut down on things that we buy, tried not to as much as possible and every penny goes back in all the time to make sure we've got what we need. ",
    " 10:01 It was quite a drastic measure that you personally took though, in order to keep on paying staff here, wasn't it? ",
  ],
  subtitleList2: [
    { time: "", text: "The childcare system in the UK is broken." },
    {
      time: "0:07",
      text: "Nurseries cost a fortune for parents,but many can barely afford to stay open.",
    },
    { time: "0:11", text: "It's about affordable childcare, it's about accessible childcare." },
    {
      time: "0:15",
      text: "Almost half of working mums are considering leaving their job,because of childcare costs.",
    },
    { time: "0:21", text: "87% rise in the number of nurseries shutting down." },
    {
      time: "0:26",
      text: "We properly loved those children,so it's not just our jobs that have gone,our hearts have gone out with them as well.",
    },
    {
      time: "0:34",
      text: "The government promised a childcare revolution earlier this year,with more free hours for families,But, as someone who's covered this area a lot,I know that it's not as simple as that.",
    },
    { time: "0:43", text: "None of this can this can be delivered." },
    { time: "0:45", text: "It won't cure it, it won't solve anything." },
    {
      time: "0:47",
      text: "So the big question is:do you think it's fixable or do we need to start again?",
    },
    {
      time: "",
      text: "A nursery closes down foreverSo we're in a rainy Huyton, near Liverpool,where a nursery has shut its doors really suddenly.",
    },
    {
      time: "1:05",
      text: "It was open on a Friday and then on the Saturday there was a sign on the gates saying that it closed for ever and 50 staff members found themselves out of a job.",
    },
    { time: "1:15", text: "These children are broken hearted, they're confused." },
    { time: "1:18", text: "We have children sobbing here, holding on to each other." },
    { time: "1:22", text: "These children are suffering." },
    {
      time: "1:24",
      text: "Transition for children is very, very important and these children have had no transition.",
    },
    {
      time: "1:30",
      text: "You took the decision at this nursery to unionise,why did you take that decision?",
    },
    { time: "1:35", text: "Because we felt we had no other choice." },
    {
      time: "1:38",
      text: "We were being paid minimum wage,which is common throughout the sector.",
    },
    { time: "1:42", text: "So many members of staff, including managers,have had second jobs." },
    {
      time: "1:48",
      text: "I've heard stories about people leaving leaving to go to Asda or Morrisons.",
    },
    { time: "1:52", text: "Because they pay more money and we had to do something." },
    {
      time: "1:55",
      text: "After we took a day of strike action,the nursery owners basically closed the nursery down without any warning to parents, staff, children or anybody.",
    },
    {
      time: "2:03",
      text: 'Every childcare worker, every care worker,needs to be standing up now and going:"I\'m worth more than this."',
    },
    {
      time: "2:10",
      text: "We need to stick together, if this can happen to us today,it can happen to you tomorrow.",
    },
    { time: "2:14", text: "This isn't just a one-off." },
    { time: "", text: "What do you do when your childcare disappears?" },
    {
      time: "2:17",
      text: "When The Orchard Day nursery locked its gates,around 200 children were suddenly left without childcare and parents had to scramble around for alternatives.",
    },
    { time: "2:35", text: "Did you have any idea that this was going to happen?" },
    { time: "2:39", text: "None, whatsoever." },
    { time: "2:40", text: "I actually couldn't believe that was allowed to happen." },
    { time: "2:47", text: "What's it been like for you?" },
    { time: "2:48", text: "It's been a long two weeks, especially from a childcare perspective." },
    { time: "2:54", text: "Our parents work, so we don't have grandparents who can take Angus." },
    { time: "2:58", text: "I work with children of Angus's age." },
    {
      time: "3:02",
      text: "I spoke to my headteacher and he very, very kindly offered to let Angusatt end the nursery setting.",
    },
    { time: "3:10", text: "That must have been a relief." },
    { time: "3:12", text: "A huge relief." },
    {
      time: "3:13",
      text: "Other families do not have a support system around them and they've had to call in work and say we can't come to work today.",
    },
    {
      time: "3:21",
      text: "They've lost money where they've paid upfront for the childcare and they've lost their pay.",
    },
    {
      time: "3:27",
      text: "What's it been like putting your children into childcare and the kind of cost there's been around that?",
    },
    { time: "3:32", text: "Our childcare has cost more than our rent each month." },
    { time: "3:36", text: "We paid around £12,000 last year." },
    {
      time: "3:39",
      text: "By the time the childcare had left my wages, I was actually working for maybe £300 per month.",
    },
    { time: "3:47", text: "It's disheartening, isn't it?" },
    { time: "3:49", text: "The thing is, Becci's situation is far from unique." },
    {
      time: "3:52",
      text: "Up and down the UK, parents are really struggling with childcare costs.",
    },
    {
      time: "3:57",
      text: "Often, they look at the sums and they think it's not feasible, we can't do thisNursery fees and childcare reforms and so one of them, usually the mother, drops out of the workforce.",
    },
    {
      time: "4:05",
      text: "But nurseries are really  struggling too and they say they can't afford the increased cost of staffing,they can't afford the increased cost of energy and they are increasingly closing their doors.",
    },
    {
      time: "4:16",
      text: "They say that the free hours that they provide at the moment aren't sufficiently funded by the government and haven't been for years.",
    },
    { time: "4:24", text: "Now, the government has promised a revolution in childcare." },
    {
      time: "4:28",
      text: "It's promised over the next two years that parents will get more support with funding, more free hours, and nurseries will get paid more per hour for each child that goes therePregnant Then Screwed and the March of the MummiesGroups like Pregnant Then Screwed have been campaigning for changes like these for years.",
    },
    { time: "4:48", text: "Do you know how much it costs for a childcare place in the UK?" },
    { time: "4:52", text: "It's about £14,000 a year." },
    { time: "4:55", text: "So what did that feel like, this moment here?" },
    { time: "4:58", text: "I mean, just incredible." },
    {
      time: "5:00",
      text: "It's such a joyful expression of anger, which is what I think makes protests like these so important.",
    },
    {
      time: "5:09",
      text: "Jeremy Hunt announced this huge new childcare package,what was your reaction?",
    },
    { time: "5:16", text: "I was elated, I was really pleased." },
    {
      time: "5:19",
      text: "There are problems with it, of course,It's absolutely not without its flaws,however, the fact that it was the most significant part of the spring budget shows that childcare is being taken very seriously.",
    },
    {
      time: "5:32",
      text: "How would you describe the current state of childcare in this country?",
    },
    { time: "5:37", text: "I mean, it's a mess, it's just an absolute mess." },
    { time: "5:42", text: "It's unaffordable, it's inaccessible, it's entirely dysfunctional." },
    {
      time: "5:47",
      text: "There's nothing good about it and if we compare it to other countries,we are falling way way behind, embarrassingly so.",
    },
    { time: "5:55", text: "Where does it better?" },
    { time: "5:57", text: "Pretty much every country does it better than we do." },
    { time: "6:01", text: "No country though, I would say, has got it spot on." },
    {
      time: "6:04",
      text: "Countries tend to focus either on the quality of provision that they're providing and seeing it really as early years education or they see it as a way to get women back into the workforce.",
    },
    { time: "6:16", text: "We are doing neither, we're failing at both." },
    {
      time: "6:19",
      text: "However, if they fail to deliver that first stage of this plan, it's political suicide.",
    },
    { time: "6:25", text: "So yes, I am confident things will now get better." },
    { time: "6:29", text: "Can't really get any worse, can they?" },
    { time: "6:30", text: "They can't get any worse, no, they really can't." },
    { time: "", text: "Childcare crisis in the UKSo it's really difficult the spring budget." },
    {
      time: "6:36",
      text: "On the one hand, it will help many parents who are really struggling at the moment,but as someone who's covered this area a lot, I know that it's not as simple as that.",
    },
    {
      time: "6:46",
      text: 'It\'s not as simple as: "Oh, this is going to fix everything," because what happens when you suddenly put loads more demand into this sector that is alreadyteetering on the brink of collapse?',
    },
    {
      time: "6:58",
      text: "So, we're going to go and speak to Neil Leitch, who is the CEO of the Early Years Alliance and see what he thinks about it.",
    },
    {
      time: "7:05",
      text: "How would you describe the state of childcare in this country at the moment?",
    },
    { time: "7:10", text: "Absolute crisis." },
    {
      time: "7:11",
      text: "This year we have seen record closures, nearly 5,500 providers have closed their doors.",
    },
    {
      time: "7:17",
      text: "I've never witnessed the recruitment and retention crisis as grave as it is now.",
    },
    {
      time: "7:22",
      text: "If this continues, you know, in commercial terms you would argue it would be a market collapse,but in real terms we prejudice the life chances of lots and lots of children.",
    },
    { time: "7:32", text: "When you heard those announcements, what was your initial reaction?" },
    {
      time: "7:39",
      text: "I probably couldn't explain on camera what my real reaction was,but definitely anger.",
    },
    { time: "7:45", text: "None of this can be delivered." },
    {
      time: "7:47",
      text: "We have settings closing, we have settings reducing their hours,we have parents struggling to get access for their three- and four-year-olds.",
    },
    {
      time: "7:55",
      text: "Why would you extend that even further, knowing that you can't cope with what you've got?",
    },
    { time: "8:00", text: "All you've done is, dare I say, pile on more pressure." },
    {
      time: "8:05",
      text: "What do you think is going to happen in the next few years when this huge increase in demand is going to come into the sector?",
    },
    {
      time: "8:10",
      text: "Well the logic says that there would be parents who will be turning up at settings,whether it be childminders, preschools or nurseries,expecting places for their children and they won't be there.",
    },
    {
      time: "",
      text: "Madcaps nursery: we need ministers who care about early years educationThis is a sector that's in a lot of trouble.",
    },
    {
      time: "8:27",
      text: "We know that nurseries are shutting their doors all the time, we know that other nurseries are really struggling to retain staff and they're just keeping their heads above water.",
    },
    {
      time: "8:39",
      text: "We've come to Madcaps nursery in Lincolnshire, where the owner has had to take extreme measures just to keep the doors open.",
    },
    { time: "8:47", text: "How long have you been open?" },
    { time: "8:48", text: "We've been open about 12 years." },
    {
      time: "8:50",
      text: "We look at what's called the curiosity approach,so the children get their hands dirty, like they are over there and they really get to enjoy it.",
    },
    { time: "8:56", text: "I can see, they're really getting into it here." },
    { time: "8:59", text: "She's busy planting things." },
    {
      time: "9:01",
      text: "What is it good early years education can bring to a child and to a family?",
    },
    { time: "9:06", text: "Security, happiness, resilience." },
    {
      time: "9:10",
      text: "Children need to know how to deal with other people, how to deal with conflict, how to share.",
    },
    {
      time: "9:15",
      text: "If you can give children that solid framework to start their lives, they've  got that for their life.",
    },
    {
      time: "9:23",
      text: "How difficult has it been over the past couple of years as a provider?",
    },
    { time: "9:27", text: "Awful." },
    {
      time: "9:28",
      text: "It's not an easy job, you've got a lot of skills, a lot of knowledge, a lot of experience and you're getting less money than somebody who works in our local supermarket, for example.",
    },
    { time: "9:36", text: "It says what do you call a gorilla wearing headphones?" },
    { time: "9:40", text: "A dancing gorilla." },
    { time: "9:42", text: 'It says "Anything you like, he can\'t hear you."' },
    {
      time: "9:47",
      text: "Talk to us about how you've coped with the financial squeeze on the nursery.",
    },
    {
      time: "9:52",
      text: "We've cut down on things that we buy, tried not to as much as possible and every penny goes back in all the time to make sure we've got what we need.",
    },
    {
      time: "10:01",
      text: "It was quite a drastic measure that you personally took though,in order to keep on paying staff here, wasn't it?",
    },
    { time: "10:07", text: "Yes, I stopped paying myself." },
    {
      time: "10:08",
      text: "I'm not required, you know, in order to look after the children,we need people in the ratios to do that, that's the priority.",
    },
    { time: "10:16", text: "But you come into work work every day or ...?" },
    { time: "10:18", text: "Nearly every day." },
    { time: "10:21", text: "Occasional weekends." },
    { time: "10:25", text: "Outside." },
    { time: "10:27", text: "You're going outside, good boy." },
    { time: "10:28", text: "Outside." },
    { time: "10:29", text: "Outside, that's right." },
    {
      time: "10:30",
      text: "Another major reform being introduced will change adult to child ratios in nurseries.",
    },
    {
      time: "10:34",
      text: "Each member of staff will be allowed to look after five two-year-olds, instead of four.",
    },
    { time: "10:39", text: "How did you feel when you heard those announcements?" },
    { time: "10:42", text: "Floored would be the best way of putting it." },
    {
      time: "10:43",
      text: 'Trying to fund more children at two and then say:"Oh, and by the way also you\'ve got to have more of them."',
    },
    { time: "10:48", text: "It's completely ridiculous." },
    { time: "10:50", text: "It's dangerous." },
    { time: "10:51", text: "It's not about the money for me, it's far more about what's safe." },
    {
      time: "10:56",
      text: "When I think about it and I think about the system that we've got and that some nurseries are run by local authorities and some are private providers, it seems really haphazard.",
    },
    { time: "11:05", text: "Exactly." },
    {
      time: "11:06",
      text: "Do you think that's a system that can be fixed or do you think we just like need to start again?",
    },
    { time: "11:10", text: "I don't think it can be fixed easily." },
    { time: "11:12", text: "It's got to have ministers and people in government who care." },
    { time: "11:16", text: "And you don't feel that they do at the moment?" },
    { time: "11:17", text: "Absolutely not!And that's the polite version." },
    {
      time: "11:28",
      text: "I just find it amazing that these people who are doing this incredibly important job,they're doing it for minimum wage and they're really struggling.",
    },
    { time: "11:39", text: "Speaking to Sue was amazing." },
    {
      time: "11:41",
      text: "Her choice was: keep my staff that I need for the ratios or pay myself.",
    },
    {
      time: "11:47",
      text: "She told us that she's retired. She hasn't retired!And at the same time you've got parents like Becci who are paying a lot of money so that their kids can go to nursery, or making massive sacrifices themselves so that they can continue to work.",
    },
    {
      time: "12:02",
      text: "But if suddenly you haven't got any childcare but you've still got your job and your partner's still got ther job and you've still got your other kid to get to school,like what do you do?",
    },
    { time: "12:11", text: "It just feels like the entire system needs an overhaul." },
    {
      time: "12:16",
      text: "It doesn't feel that we are doing the right thing for the youngest people in our society.",
    },
  ],
};
